version: '3.6'
services:

  viewer:
    image: nginx:1.19.5-alpine
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '81:81'
    networks:
      - frontend
      - backend
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ${VIEWER_CONFIG}:/usr/share/nginx/html/app-config.js:ro
      - ${VIEWER_DIST}:/usr/share/nginx/html/:ro
    environment:
      - TZ=Asia/Shanghai

  orthanc:
    image: osimis/orthanc:20.11.2
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    ports:
    #   - '8042:8042'
      - '4242:4242'
    networks:
      - frontend
      - backend
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ${ORTHANC_DB_MNT}:/var/lib/orthanc/db
    environment:
      # DICOMWeb Plugin
      - DW_ENABLED=true
      # Postgres Plugin
      - PG_ENABLED=true
      - TZ=Asia/Shanghai
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:13.1
    container_name: postgres
    networks:
      - backend
    volumes:
      - ${POSTGRES_DATA_MNT}:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=orthanc
      - TZ=Asia/Shanghai

networks:
  frontend:
  backend:
